### ISSUE TITLE
How can I create custom tile data?

### ISSUE THREAD

**Issue by barkhaneum** [smartgov-liris/lez-viewer#19]
Hello your project is so interesting. Is there any way to create user-defined tile data? I want to create a file like lez_1_tiles.json .

**Comment by vdeslandres** [comment]
Hi Barkhaneum,

Thanks for your message.
Data are the core of the material of the project: our data were provided by the LAET lab: http://www.laet.science/?lang=en.
The json file depends on what you're working on.
We have used OSM exports and add the data provided by the LAET lab.
The given examples may help to produce similar data, but you have to build them with your own resources.

Please, give us news about your advancement!
